Consistently replace '_' with '-' in hostnames
ipspace/netlab pull request #1619
Opened 2024-12-07 14:43 UTC by jbemmel

It is not a valid FQDN character, and some platforms (like Cumulus NVUE) fail with an error

We could consider restricting node names to be valid FQDNs (of at most 16 characters), and/or apply the 'replace' normalization in Python rather than all templates (either define a ```node.hostname``` property and use that everywhere instead of ```inventory_hostname```, or change ```inventory_hostname``` (and issue an error when troublesome node names are used)

2024-12-07 17:29 UTC, ipspace requested changes
There is no need for such a change. Many platforms accept both.

Whichever platform cannot deal with a valid node identifier should solve its own issues in a configuration template.

Also:

* Did you test all these changes? Are you sure they work?
* Why did you not change the hostname mappings if you want to enforce consistency?

Just because you have a problem with NVUE does not mean everything else has to change. Submit a PR for those platforms that cannot handle '_' and I'll merge it.

2024-12-09 04:30 UTC, jbemmel commented
> There is no need for such a change. Many platforms accept both.
> 
> Whichever platform cannot deal with a valid node identifier should solve its own issues in a configuration template.
> 
> Also:
> 
> * Did you test all these changes? Are you sure they work?
> * Why did you not change the hostname mappings if you want to enforce consistency?
> 
> Just because you have a problem with NVUE does not mean everything else has to change. Submit a PR for those platforms that cannot handle '_' and I'll merge it.

Many platforms accept both, Ubuntu for example simply ignores the '_' characters and a ```r_1``` hostname becomes ```r1```.

Most of the platforms I have access to - eos, cumulus, dell os10, linux - use the character substitution. The immediate issue was with Cumulus NVUE, but - for example - Cisco AVA is [reported](https://github.com/GNS3/gns3-gui/issues/3524) to have similar issues.

I think users would be better off if they stayed away from using '_' in hostnames, lacking that the next best thing is - imho - to replace '_' with '-', rather than let it be ignored and hope it doesn't cause issues. We could make that configurable, while I did not test the other platforms I think it is reasonable to expect the hostname with a '-' to have a better chance to work.

I can submit a PR for only Cumulus NVUE, I do not have access to most other platforms so I don't really care for myself. But I thought it'd be nice for the community

2024-12-09 07:45 UTC, ipspace commented
> I can submit a PR for only Cumulus NVUE

You should have done that in the first place.

> I do not have access to most other platforms so I don't really care for myself.

Copiously illustrated in #1623.

Also: stop "fixing" stuff you don't care about and have no intention of testing.

> But I thought it'd be nice for the community

Maybe it's just me, but in my personal opinion the community might appreciate a tested and working software more.

2024-12-23 05:55 UTC, ipspace commented
Still waiting for the changes to be implemented. Converting to draft.

2024-12-23 17:08 UTC, closed without merging

2024-12-23 17:08 UTC, jbemmel commented
Replaced by https://github.com/ipspace/netlab/pull/1682